### ISSUE TITLE
Tests can't run using node v12

### ISSUE THREAD

**Issue by raman-nbg** [dmurvihill/firebase-mock#44]
Running `npm test` using node in version 12+ is not possible.

It throws the following error:
```
> firebase-mock@2.2.10 test /Users/raman/dev/github/raman-nbg/firebase-mock-backup
> gulp lint && gulp test

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/raman/dev/github/raman-nbg/firebase-mock-backup/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/raman/dev/github/raman-nbg/firebase-mock-backup/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/raman/dev/github/raman-nbg/firebase-mock-backup/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
npm ERR! Test failed.  See above for more details.
```

According to [Stackoverflow](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node) it should be fixable updating to gulp 3 but I didn't try yet.

**Comment by dmurvihill** [comment]
You need Gulp 4+. Pull `dmurvihill:master` and you should get it.
